CREATE OR REPLACE TRIGGER audit_update
BEFORE DELETE OR UPDATE ON audit_d
BEGIN
  IF TO_NUMBER(TO_CHAR(SYSDATE, 'HH24')) NOT BETWEEN 9 AND 18 THEN
    RAISE_APPLICATION_ERROR(-20003, 'Updates/deletes allowed only between 9 AM and 6 PM');
  END IF;
END;
/
