CREATE OR REPLACE TRIGGER audit_insert
BEFORE DELETE OR INSERT ON audit_d
BEGIN
  IF TO_NUMBER(TO_CHAR(SYSDATE, 'HH24')) NOT BETWEEN 9 AND 18 THEN
    RAISE_APPLICATION_ERROR(-20003, 'insert/deletes allowed only between 9 AM and 6 PM');
  END IF;
END;
/

